import type { Metadata } from "next";

import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { auth } from "@/auth";
import { SessionProvider } from "next-auth/react";
import {Plus_Jakarta_Sans} from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import React from "react";
 

const jakarta = Plus_Jakarta_Sans({subsets:["latin"]})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await auth()

  return (
    <SessionProvider session={session}>
    <html lang="en">
      <body
       className={jakarta.className}
      >
        <React.StrictMode>
         <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        {children}
        <Toaster />
        </ThemeProvider>
        </React.StrictMode>
      </body>
    </html>
    </SessionProvider>
  );
}
